# Generated by Django 3.1.5 on 2021-05-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gossip', '0002_remove_character_gossiplist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gossip',
            old_name='expiredDate',
            new_name='pubDate',
        ),
    ]
