# Generated by Django 3.1.5 on 2021-05-06 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gossip', '0003_auto_20210503_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='gossip',
            name='EndDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gossip',
            name='pubDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
